-
  version: 1.0.{build}
  image: Visual Studio 2017
  clone_depth: 1
  branches:
    except:
      - master
  install:
  - set PATH=C:\Ruby25\bin;%PATH%
  - gem install bundler --no-document
  - bundle install
  build_script:
  - bundle exec rake
  test: off
  artifacts:
  - path: build\pkg\DotNetZip.*.nupkg
    name: Nuget Package
-
  version: 1.0.{build}
  image: Visual Studio 2017
  clone_depth: 1
  branches:
    only:
      - master
  install:
  - set PATH=C:\Ruby25\bin;%PATH%
  - gem install bundler --no-document
  - bundle install
  build_script:
  - bundle exec rake
  test: off
  artifacts:
  - path: build\pkg\*.nupkg
    name: Nuget Package
  deploy:
  - provider: NuGet
    api_key:
      secure: VbOAwqtj8Rocu3zOsuszfOtRQqGhT5FY0ObyGKBrBAZHgRYLCVhIv6tKFzR1cIRD
    skip_symbols: true
    artifact: /.*\.nupkg/ 
